### ISSUE TITLE
Crash downloading permissions

### ISSUE THREAD

**Issue by kevinlehtiniitty** [alecgorge/AdminiumIssues#11]
After adding a new server the app keeps crashing "downloading permissions"

JSONAPI 5.1.1
Server log:
16:56:52 [INFO] [JSONAPI] [API Request] kevinlehtiniitty requested: jsonapi.users.user.permissions(["kevinlehtiniitty"]){AUTHED, ALLOWED} plugins.name.version(["JSONAPI"]){AUTHED, ALLOWED}

**Comment by alecgorge** [comment]
I can't make this happen. Once the next beta is released I'll have better crash reporting that will help me identify this.
