### ISSUE TITLE
Crash on iOS 7 Beta 6

### ISSUE THREAD

**Issue by ghost** [alecgorge/AdminiumIssues#14]
The app crashes at launch on iOS 7 beta 6.

iPod Touch 5 - 32 Gb

**Comment by Bepatt** [comment]
I am having the same problem. Ios 7 beta 6 iPhone 4S

**Comment by ChrisLane** [comment]
iPhone 4S and iOS7 beta 6 work fine for me. Using the second adminium beta.

**Comment by Bepatt** [comment]
2nd beta?

**Comment by kevinlehtiniitty** [comment]
Technically beta 1...the first build that was sent out to a smaller group was an alpha build.

**Comment by ghost** [comment]
Where is the 2nd beta ???

**Comment by ChrisLane** [comment]
There isn't one, ignore what I said.

**Comment by ghost** [comment]
The Adminium beta 2 is here but i have the same problem :(

**Comment by alecgorge** [comment]
This has been resolved since beta 4
