### ISSUE TITLE
Add more information to overview screen for people who can't see graphs

### ISSUE THREAD

**Issue by alecgorge** [alecgorge/AdminiumIssues#30]

**Comment by alecgorge** [comment]
@godgodgodgo @kevinlehtiniitty any suggestions of what to put there?

**Comment by ChrisLane** [comment]
There's an overview? O_O
TPS, loaded chunks per world, players, entities, drive space, memory usage, mc version, no. plugins loaded

**Comment by alecgorge** [comment]
What about for users who aren't allowed to view server performance
information?

Sent from my iPhone

On Oct 2, 2013, at 5:25 AM, godgodgodgo notifications@github.com wrote:

There's an overview? O_O
TPS, loaded chunks per world, players, entities, drive space, memory usage

—
Reply to this email directly or view it on
GitHubhttps://github.com/alecgorge/AdminiumIssues/issues/30#issuecomment-25534132
.

**Comment by ChrisLane** [comment]
probably just the non performance related things I guess like mc version and players....that's about it.
