### ISSUE TITLE
I need JSONAPI 5.2.4

### ISSUE THREAD

**Issue by ghost** [alecgorge/AdminiumIssues#31]
Where can I download it please ?

**Comment by alecgorge** [comment]
http://ci.alecgorge.com/job/JSONAPI/

Look on the left for the latest build for the version of minecraft you are
running.

There are also direct links in the test flight email.

Sent from my iPhone

On Oct 5, 2013, at 12:18 AM, Adrien CORCILIUS notifications@github.com
wrote:

Where can I download it please ?

—
Reply to this email directly or view it on
GitHubhttps://github.com/alecgorge/AdminiumIssues/issues/31
.

**Comment by ghost** [comment]
Thank you :)
