### ISSUE TITLE
Crash when trying to connect to a server

### ISSUE THREAD

**Issue by ghost** [alecgorge/AdminiumIssues#32]
I can't connect to a server with to 2 lasts beta (7 and 8).
Maybe it's because i haven't the RemoteToolkitPlugin and Vault ??

Server : 1.6.2, JSONAPI : 5.2.5. Ports properly forwarded...

**Comment by alecgorge** [comment]
Any errors in the server console? Any errors in Adminium?

**Comment by ghost** [comment]
You can watch this little video : http://youtu.be/wvqj0fjRzeI .
Log file here : https://mega.co.nz/#!dYhRhbKB!atSvuR55MrjV7jxElaGS6y1oLExBjKqzr6-BI9OopKM

No error in Adminium and in the console...

**Comment by alecgorge** [comment]
Delete config.yml and users.yml and restart the server. I fixed a bug relating to this I think in 5.2.5

**Comment by ghost** [comment]
Sorry, it does not work.

In the JSONAPI users.yml I have a username and a password
When I type a false password in Adminium, the app connects to the server and I can't anything in "Overview".
But when I type the right password, the app crashes when downloading server informations... 

Thanks for your help =D
