### ISSUE TITLE
Lock user's chat name

### ISSUE THREAD

**Issue by ChrisLane** [alecgorge/AdminiumIssues#36]
The ability to lock a user's chat name in the user file would be good to ensure people aren't changing their names all the time and we know who is who.

This would also give the ability for people with automated payment systems to give their users access to an account with chat access for example.
More payments to servers + more people buying the app.
Just an idea, doubt that would happen considering the price of the app too and there are free alternatives for chat.

Anyway, locking user chat names would be good to ensure my moderators don't mess around and impersonate people.

**Comment by alecgorge** [comment]
I had intended on doing this from the get go. I even have a permission node written down for it. I just forgot to implement it.

Time to pull the build from Apple...
