### ISSUE TITLE
App claims server has wrong version

### ISSUE THREAD

**Issue by ChrisLane** [alecgorge/AdminiumIssues#54]
When the server does not have vault installed, Adminium will claim that it does not have the required JSONAPI version to connect to the server.

I have tested this on an MCPC-Plus server with the Direwolf20 FTB pack.

MCPC-Plus: build 190
JSONAPI: build 55
Adminium: 3.0.3

Direwolf20 pack: 1.0.7 <-- most likely not relevant.

**Comment by alecgorge** [comment]
I've made Vault a hard dependency for JSONAPI so that should take care of this.
