### ISSUE TITLE
Bugged chat text box position

### ISSUE THREAD

**Issue by ChrisLane** [alecgorge/AdminiumIssues#55]
When changing a chat setting and then going back into the chat, the text box can get stuck in the centre of the screen.

Steps to reproduce:
1. Enter 'Chat Name' in the chat settins
2 Click the 'Chat' button to go back to the chat screen without pressing 'return' on the keyboard to dismiss it.
3. The text box is in the centre of the screen.

This really does't matter much but it's a bug ;)

**Comment by alecgorge** [comment]
Fixed for 3.1.0
