### ISSUE TITLE
players don't change game mode but stay in adventure mode no matter what you do

### ISSUE THREAD

**Issue by kevinlehtiniitty** [alecgorge/AdminiumIssues#64]

**Comment by alecgorge** [comment]
cannot reproduce

**Comment by alecgorge** [comment]
reproduced and fixed in JSONAPI. Build #79 on Jenkins should fix it.

**Comment by alecgorge** [comment]
Just kidding, build #81

**Comment by alecgorge** [comment]
just kidding again, it is actually a bug in adminium that is now fixed
