### ISSUE TITLE
Editing server connection details

### ISSUE THREAD

**Issue by ChrisLane** [alecgorge/AdminiumIssues#7]
I have three servers in adminium from the previous version.

I edit the first server's details (everything is fine)
I go to edit the second server's details and it shows the first servers details instead.
Upon redoing the second server's details and saving it saves changes of the IP (possibly username and password too) to the first server entry.

**Comment by alecgorge** [comment]
Unfortunately this is actually a bug in iOS. It works fine in iOS 7 thankfully...
